-- ============================================================
-- Dragon Media — Supabase Production Schema Notice
-- ============================================================
--
-- IMPORTANT:
--
-- This file is NOT the production database source of truth.
--
-- The live Dragon Media database is managed by Supabase migrations
-- and the Supabase project itself.
--
-- Project:
--   dragon-media
--
-- Project Ref:
--   pukqeiagqjqketcecipz
--
-- Production schema contains additional systems that were added
-- after the original bootstrap schema, including:
--
-- - Multi-tenant organizations
-- - Users / roles / permissions
-- - CRM
-- - Leads / customers / deals
-- - Pipeline stages
-- - Tasks / activities
-- - Services
-- - Campaigns
-- - Omnichannel conversations / messages
-- - WhatsApp / Meta integrations
-- - Ryan AI
-- - Ryan usage / credits / purchases
-- - Plans
-- - Subscriptions
-- - Entitlements
-- - Invoices / payments
-- - Payment requests
-- - Payment methods
-- - Notifications
-- - Platform settings
-- - Branding settings
-- - Audit logs
-- - Automation engine
-- - RLS policies
-- - Security-definer functions
-- - WhatsApp outbound processing
-- - Subscription expiry processing
--
-- The previous version of this file was an obsolete bootstrap schema
-- and was incomplete. It must NOT be executed against production.
--
-- Reproducible production database changes MUST be created as
-- Supabase migrations.
--
-- Never use this file to recreate or overwrite the production DB.
--
-- ============================================================
