import React, { useEffect, useState } from 'react'
import { Card } from '../components/ui'
import { supabase } from '../lib/supabaseClient'

type Package = { id:string; name:string; messages:number; price:number; currency:string; description:string|null; status:'active'|'inactive'; sort_order:number; is_popular:boolean }
type Form = Omit<Package,'id'>
const empty:Form={name:'',messages:1000,price:150,currency:'EGP',description:'',status:'active',sort_order:1,is_popular:false}
export default function AdminRyanPackages(){
 const [items,setItems]=useState<Package[]>([]),[form,setForm]=useState<Form>(empty),[editing,setEditing]=useState<string|null>(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState('')
 const load=async()=>{if(!supabase){setError('قاعدة البيانات غير متاحة.');setLoading(false);return} setLoading(true); const {data,error:e}=await supabase.from('ryan_message_packages').select('id,name,messages,price,currency,description,status,sort_order,is_popular').order('sort_order',{ascending:true}); if(e)setError('تعذر تحميل باقات Ryan.'); else setItems((data??[]) as Package[]); setLoading(false)}
 useEffect(()=>{void load()},[])
 const save=async()=>{if(!supabase)return; setError('');setSuccess(''); if(!form.name.trim()||form.messages<=0||form.price<0){setError('راجع اسم الباقة وعدد الرسائل والسعر.');return} setSaving(true); const payload={...form,name:form.name.trim(),description:form.description?.trim()||null}; const q=editing?supabase.from('ryan_message_packages').update(payload).eq('id',editing):supabase.from('ryan_message_packages').insert(payload); const {error:e}=await q; if(e)setError(e.message); else {setSuccess(editing?'تم تحديث الباقة.':'تم إنشاء الباقة.');setForm(empty);setEditing(null);await load()} setSaving(false)}
 const edit=(p:Package)=>{setEditing(p.id);setForm({name:p.name,messages:p.messages,price:Number(p.price),currency:p.currency,description:p.description||'',status:p.status,sort_order:p.sort_order,is_popular:p.is_popular})}
 const remove=async(id:string)=>{if(!supabase||!window.confirm('حذف باقة Ryan؟'))return; const {error:e}=await supabase.from('ryan_message_packages').delete().eq('id',id); if(e)setError(e.message); else await load()}
 return <div dir="rtl" className="space-y-6 dm-page-enter">
  <div className="rounded-3xl bg-gradient-to-l from-[#071f45] to-[#123b75] p-6 text-white shadow-xl"><div className="flex flex-wrap items-start justify-between gap-4"><div><span className="inline-flex rounded-full border border-cyan-300/20 bg-cyan-300/10 px-3 py-1 text-xs font-bold text-cyan-100">RYAN AI</span><h1 className="mt-3 text-2xl font-black">باقات رسائل Ryan</h1><p className="mt-2 max-w-2xl text-sm leading-7 text-white/65">أنشئ وعدّل باقات الرسائل التي تظهر للعملاء. السعر وعدد الرسائل مصدرهما هذه الصفحة فقط.</p></div><div className="rounded-2xl border border-white/10 bg-white/5 px-4 py-3 text-xs text-white/65">إدارة من الكنترول بانل</div></div></div>
  {error&&<div className="rounded-2xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}{success&&<div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-700">{success}</div>}
  <Card className="p-5 sm:p-6"><div className="mb-5 flex items-center justify-between gap-3"><div><h2 className="text-lg font-black text-ink-950">{editing?'تعديل الباقة':'إضافة باقة جديدة'}</h2><p className="mt-1 text-xs text-ink-900/50">كل التغييرات تظهر فورًا في صفحة الفوترة بعد الحفظ.</p></div>{editing&&<button className="rounded-xl border border-ink-900/10 px-3 py-2 text-xs font-bold" onClick={()=>{setEditing(null);setForm(empty)}}>إلغاء</button>}</div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><label className="text-xs font-semibold">اسم الباقة<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} className="mt-1 w-full rounded-xl border p-3 text-sm"/></label><label className="text-xs font-semibold">عدد الرسائل<input type="number" min="1" value={form.messages} onChange={e=>setForm({...form,messages:Number(e.target.value)})} className="mt-1 w-full rounded-xl border p-3 text-sm"/></label><label className="text-xs font-semibold">السعر<input type="number" min="0" step="0.01" value={form.price} onChange={e=>setForm({...form,price:Number(e.target.value)})} className="mt-1 w-full rounded-xl border p-3 text-sm"/></label><label className="text-xs font-semibold">الترتيب<input type="number" min="0" value={form.sort_order} onChange={e=>setForm({...form,sort_order:Number(e.target.value)})} className="mt-1 w-full rounded-xl border p-3 text-sm"/></label></div><textarea value={form.description||''} onChange={e=>setForm({...form,description:e.target.value})} rows={2} placeholder="وصف مختصر" className="mt-4 w-full rounded-xl border p-3 text-sm"/><div className="mt-4 flex flex-wrap items-center gap-5 text-sm"><label className="flex items-center gap-2"><input type="checkbox" checked={form.is_popular} onChange={e=>setForm({...form,is_popular:e.target.checked})}/> الأكثر طلبًا</label><label className="flex items-center gap-2"><input type="checkbox" checked={form.status==='active'} onChange={e=>setForm({...form,status:e.target.checked?'active':'inactive'})}/> متاحة للعملاء</label><button disabled={saving} onClick={()=>void save()} className="mr-auto rounded-xl bg-ink-950 px-5 py-3 text-sm font-bold text-white disabled:opacity-50">{saving?'جارٍ الحفظ...':editing?'حفظ التعديلات':'إضافة الباقة'}</button></div></Card>
  <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{loading?[1,2,3].map(i=><div key={i} className="h-56 animate-pulse rounded-3xl bg-ink-900/5"/>):items.map(p=><Card key={p.id} className="group p-6 transition-all hover:-translate-y-1 hover:shadow-xl"><div className="flex items-center justify-between gap-2"><h2 className="font-black text-ink-950">{p.name}</h2><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${p.status==='active'?'bg-emerald-50 text-emerald-700':'bg-sand-100 text-sand-600'}`}>{p.status==='active'?'متاحة':'متوقفة'}</span></div><div className="mt-5 text-3xl font-black text-blue-700">{p.messages.toLocaleString('ar-EG')} <span className="text-xs text-ink-900/45">رسالة</span></div><div className="mt-2 text-lg font-black text-ink-950">{Number(p.price).toLocaleString('ar-EG')} {p.currency}</div>{p.description&&<p className="mt-2 text-xs leading-5 text-ink-900/50">{p.description}</p>}<div className="mt-5 flex gap-2"><button onClick={()=>edit(p)} className="flex-1 rounded-xl border px-3 py-2 text-sm font-bold">تعديل</button><button onClick={()=>void remove(p.id)} className="rounded-xl border border-red-100 px-3 py-2 text-sm font-bold text-red-700">حذف</button></div></Card>)}</div>
 </div>
}
