import React from 'react'
import { Link } from 'react-router-dom'
import { useBranding } from '../hooks/useBranding'

function Icon({children,className='w-6 h-6'}:{children:React.ReactNode;className?:string}){return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" className={className} aria-hidden="true">{children}</svg>}

const features=[
{title:'إدارة العملاء CRM',description:'نظّم العملاء والفرص والصفقات في مكان واحد، وتابع كل عميل من أول تواصل لحد إتمام البيع.',icon:<Icon><path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M22 21v-2a4 4 0 0 0-3-3.87"/><path d="M16 3.13a4 4 0 0 1 0 7.75"/></Icon>},
{title:'المبيعات والصفقات',description:'تابع مراحل البيع والمهام والمتابعات واعرف أين تقف كل فرصة.',icon:<Icon><path d="M3 3v18h18"/><path d="m7 16 4-5 3 3 5-7"/></Icon>},
{title:'التسويق والحملات',description:'أنشئ حملاتك وتابع نتائجها ونظّم جمهورك من مساحة عمل واحدة.',icon:<Icon><path d="M4 11a9 9 0 0 1 16 0"/><path d="M4 11v6a2 2 0 0 0 2 2h2v-8H4Z"/><path d="M20 11v6a2 2 0 0 1-2 2h-2v-8h4Z"/><path d="M12 3v2"/></Icon>},
{title:'صندوق محادثات موحّد',description:'اجمع محادثات قنوات التواصل في تجربة منظمة وسريعة.',icon:<Icon><path d="M21 11.5a8.38 8.38 0 0 1-9 8.5 9.77 9.77 0 0 1-4-.8L3 21l1.8-4A8.36 8.36 0 0 1 3 11.5 8.5 8.5 0 0 1 12 3a8.5 8.5 0 0 1 9 8.5Z"/><path d="M8 12h.01M12 12h.01M16 12h.01"/></Icon>},
{title:'Ryan AI',description:'مساعد ذكي يساعدك في فهم المحادثات والتعامل مع العملاء بصورة طبيعية.',icon:<Icon><path d="M12 3v3M5.6 5.6l2.1 2.1M3 12h3M5.6 18.4l2.1-2.1M18.4 18.4l-2.1-2.1M21 12h-3M18.4 5.6l-2.1 2.1M12 18v3"/><circle cx="12" cy="12" r="4"/></Icon>},
{title:'تقارير ورؤية أوضح',description:'حوّل بيانات نشاطك إلى مؤشرات تساعدك على اتخاذ قرارات أسرع.',icon:<Icon><path d="M4 19V5"/><path d="M4 19h16"/><path d="m7 15 3-4 3 2 4-6"/></Icon>},
]

export default function Landing(){
const {branding}=useBranding()
const description='إدارة العملاء والمبيعات والتسويق وخدمة العملاء من مكان واحد.'
return <div className="min-h-screen bg-white text-ink-950">
<header className="sticky top-0 z-40 border-b border-blue-100 bg-white/90 backdrop-blur-xl"><div className="max-w-7xl mx-auto px-5 sm:px-6 lg:px-8 h-20 flex items-center justify-between gap-6"><Link to="/" className="flex items-center gap-3 shrink-0"><img src={branding.logoUrl} alt={branding.platformName} className="h-10 w-auto object-contain"/><span className="font-black text-lg hidden sm:block">{branding.platformName}</span></Link><nav className="dm-landing-nav hidden md:flex items-center gap-2 text-sm text-ink-900/65"><a href="#features" className="rounded-xl px-4 py-2.5 hover:bg-white hover:text-ink-950 transition-colors">المميزات</a><a href="#how-it-works" className="rounded-xl px-4 py-2.5 hover:bg-white hover:text-ink-950 transition-colors">طريقة العمل</a><a href="#ryan" className="rounded-xl px-4 py-2.5 hover:bg-white hover:text-ink-950 transition-colors">Ryan AI</a></nav><div className="flex items-center gap-2"><Link to="/login" className="hidden sm:inline-flex rounded-xl px-4 py-2.5 text-sm font-bold text-blue-800 hover:bg-blue-50">تسجيل الدخول</Link><Link to="/signup" className="inline-flex rounded-xl bg-blue-700 px-5 py-3 text-sm font-black text-white shadow-lg shadow-blue-700/20 hover:bg-blue-800 transition">ابدأ الآن</Link></div></div></header>
<main>
<section className="dm-landing-hero relative overflow-hidden py-20 lg:py-28"><div className="absolute inset-0 pointer-events-none"><div className="absolute -top-32 -inset-inline-end-20 w-96 h-96 rounded-full bg-blue-200/30 blur-3xl"/><div className="absolute bottom-0 inset-inline-start-0 w-80 h-80 rounded-full bg-amber-100/35 blur-3xl"/></div><div className="relative max-w-7xl mx-auto px-5 sm:px-6 lg:px-8 text-center"><div className="inline-flex items-center gap-2 rounded-full border border-blue-100 bg-white/80 px-4 py-2 text-xs font-bold text-blue-800 shadow-sm"><span className="w-2 h-2 rounded-full bg-cyan-400"/> منصة واحدة لإدارة رحلة العميل</div><h1 className="mt-7 text-4xl sm:text-5xl lg:text-6xl font-black tracking-tight leading-tight">إدارة العملاء والمبيعات<br/><span className="text-blue-700">والتسويق من مكان واحد</span></h1><p className="max-w-2xl mx-auto mt-6 text-base sm:text-lg lg:text-xl leading-8 text-ink-900/60">{description}</p><div className="flex flex-col sm:flex-row items-center justify-center gap-3 mt-8"><Link to="/signup" className="w-full sm:w-auto rounded-xl bg-blue-700 px-7 py-3.5 text-white font-black shadow-xl shadow-blue-700/20 hover:bg-blue-800 transition">ابدأ تجربة المنصة</Link><a href="#features" className="w-full sm:w-auto rounded-xl border border-blue-100 bg-white px-7 py-3.5 text-blue-800 font-bold hover:border-blue-200 transition">استكشف المميزات</a></div><div className="dm-gold-line mx-auto mt-10"/></div></section>
<section id="features" className="relative py-20 lg:py-28 bg-white border-y border-blue-100 overflow-hidden"><div className="absolute top-16 inset-inline-start-10 dm-gold-ornament" aria-hidden="true"/><div className="max-w-7xl mx-auto px-5 sm:px-6 lg:px-8"><div className="max-w-2xl mb-12"><span className="text-sm font-bold text-gold-600">كل أدواتك في مكان واحد</span><h2 className="mt-3 text-3xl lg:text-4xl font-black">منصة مصممة لنمو نشاطك</h2><p className="mt-4 text-ink-900/55 leading-8">بدل ما تشتت فريقك بين أدوات كثيرة، اجمع أهم عمليات العمل والعملاء والمبيعات في تجربة واحدة.</p></div><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-5">{features.map((feature)=><article key={feature.title} className="group relative rounded-2xl border border-blue-100 bg-white p-6 hover:-translate-y-1 hover:border-blue-200 hover:shadow-xl hover:shadow-blue-950/8 transition-all"><div className="w-12 h-12 rounded-xl bg-blue-50 text-blue-700 flex items-center justify-center">{feature.icon}</div><div className="absolute top-5 inset-inline-end-5 h-px w-10 bg-gradient-to-l from-amber-500/70 to-transparent"/><h3 className="font-black text-lg mt-6">{feature.title}</h3><p className="mt-3 text-sm leading-7 text-ink-900/55">{feature.description}</p></article>)}</div></div></section>
<section id="ryan" className="relative py-20 lg:py-28 bg-[#f7faff] overflow-hidden"><div className="max-w-7xl mx-auto px-5 sm:px-6 lg:px-8 grid lg:grid-cols-2 gap-12 items-center"><div><span className="inline-flex rounded-full border border-blue-100 bg-blue-50 px-4 py-2 text-xs font-bold text-blue-800">الذكاء الاصطناعي داخل المنصة</span><h2 className="mt-5 text-3xl lg:text-4xl font-black">Ryan AI — موظفك الذكي لخدمة العملاء</h2><p className="text-ink-900/60 leading-8 mt-6 max-w-xl">مساعد ذكي مصمم لفهم سياق المحادثة والتعامل مع العميل بصورة طبيعية، مع الاستفادة من بيانات المنصة وقاعدة المعرفة.</p><div className="mt-7 space-y-3">{['يفهم سياق المحادثة بدل الردود المحفوظة','يساعد في جمع بيانات العميل ومتابعته','مصمم لتجربة محادثة عربية طبيعية'].map(x=><div key={x} className="flex items-center gap-3 rounded-xl border border-blue-100 bg-white p-4"><span className="w-6 h-6 rounded-full bg-blue-700 text-white flex items-center justify-center">✓</span><span className="text-sm font-semibold text-ink-950">{x}</span></div>)}</div></div><div className="relative"><div className="absolute -inset-10 bg-blue-500/10 blur-3xl rounded-full"/><div className="relative rounded-3xl border border-blue-900/30 bg-[#071f45] p-5 shadow-2xl shadow-blue-950/20 overflow-hidden"><div className="absolute top-0 inset-inline-end-0 h-px w-40 bg-gradient-to-l from-cyan-300/80 to-transparent"/><div className="flex items-center gap-3 border-b border-white/10 pb-4"><div className="w-11 h-11 rounded-full bg-cyan-300 text-[#071f45] flex items-center justify-center font-black">R</div><div><div className="font-black text-white">Ryan AI</div><div className="text-xs text-cyan-200 mt-1">مساعد Dragon Media</div></div></div><div className="space-y-4 py-6"><div className="max-w-[80%] rounded-2xl rounded-tr-md bg-white/10 p-4 text-sm leading-7 text-white/90">أهلاً بحضرتك، أنا ريان. أقدر أساعدك إزاي النهاردة؟</div><div className="max-w-[75%] mr-auto rounded-2xl rounded-tl-md bg-cyan-300 text-[#071f45] p-4 text-sm leading-7 font-semibold">محتاج أعرف خدماتكم وأسعارها.</div><div className="max-w-[80%] rounded-2xl rounded-tr-md bg-white/10 p-4 text-sm leading-7 text-white/90">أكيد، خليني أعرف احتياج حضرتك الأول وأرشح لك الأنسب.</div></div><div className="rounded-xl bg-white/5 border border-white/10 px-4 py-3 text-xs text-white/55">محادثة ذكية مبنية على سياق العميل</div></div></div></div></section>
<section id="how-it-works" className="relative py-20 lg:py-28 bg-sand-50 overflow-hidden"><div className="absolute top-10 inset-inline-end-10 dm-gold-ornament" aria-hidden="true"/><div className="max-w-7xl mx-auto px-5 sm:px-6 lg:px-8"><div className="max-w-2xl"><span className="text-sm font-bold text-gold-600">طريقة العمل</span><h2 className="mt-3 text-3xl lg:text-4xl font-black">ابدأ ببساطة وتوسع مع نشاطك</h2><p className="mt-4 text-ink-900/55 leading-8">أنشئ مساحة عملك، أضف فريقك وخدماتك، ثم ابدأ إدارة العملاء والمبيعات من لوحة واحدة.</p></div><div className="grid md:grid-cols-3 gap-5 mt-10">{[['01','أنشئ مساحة عملك','أدخل بيانات نشاطك وابدأ إعداد المنصة.'],['02','نظّم عملاءك ومبيعاتك','استخدم CRM والمهام والصفقات لمتابعة كل فرصة.'],['03','طوّر التشغيل','اربط قنواتك وأدواتك واستفد من الأتمتة وRyan AI.']].map(([n,t,d])=><div key={n} className="rounded-2xl bg-white border border-sand-200 p-6 shadow-sm"><span className="text-sm font-black text-blue-700">{n}</span><h3 className="mt-4 font-black text-lg">{t}</h3><p className="mt-2 text-sm leading-7 text-ink-900/55">{d}</p></div>)}</div></div></section>
<section className="py-20 lg:py-24 bg-blue-700 text-white"><div className="max-w-5xl mx-auto px-5 text-center"><h2 className="text-3xl lg:text-4xl font-black">جاهز تدير نشاطك باحترافية أكبر؟</h2><p className="mt-4 text-white/75 leading-8">ابدأ مساحة عملك واجمع إدارة العملاء والمبيعات والتسويق في مكان واحد.</p><Link to="/signup" className="inline-flex mt-8 rounded-xl bg-white px-7 py-3.5 text-blue-800 font-black shadow-xl hover:bg-blue-50 transition">ابدأ الآن</Link></div></section>
</main><footer className="border-t border-blue-100 bg-white py-8"><div className="max-w-7xl mx-auto px-5 flex flex-col sm:flex-row gap-3 justify-between text-sm text-ink-900/45"><span>© {new Date().getFullYear()} {branding.platformName}</span><div className="flex gap-5"><Link to="/privacy" className="hover:text-blue-700">الخصوصية</Link><Link to="/terms" className="hover:text-blue-700">الشروط</Link></div></div></footer></div>
}
